services:
  db:
    image: postgres:14
    container_name: x-clone-db-prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  
  redis:
    image: redis:7
    container_name: x-clone-redis-prod
    volumes:
      - redis-data-prod:/data
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: x-clone-api-prod
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres-data-prod:
    driver: local
  redis-data-prod:
    driver: local


